
### crear productos
POST http://localhost:2000/api/v1/productos HTTP/1.1
Content-Type: application/json

{
    "nombre":"anestecia",
    "unidades":"1",
    "costo":"2000",
    "laboratorio":"genfar",
    "precio":"2000",
}

#### metrica productos 

GET http://localhost:2000/api/v1/metrica/productos HTTP/1.1
Content-Type: application/json

##### credito 
GET http://localhost:2000/api/v1/metrica/creditos HTTP/1.1
Content-Type: application/json
##### deuda 
GET http://localhost:2000/api/v1/metrica/deudas HTTP/1.1
Content-Type: application/json


######## deudas #############

GET http://localhost:2000/api/v1/deudas/1 HTTP/1.1
Content-Type: application/json
### crear deudas 
POST http://localhost:2000/api/v1/deudas HTTP/1.1
Content-Type: application/json

{
    "nombre": "jhon anderson", 
    "celular": "3128982063",
    "date": "juni 2023",
}
#### pedir registro de suma de las deudas
GET http://localhost:2000/api/v1/add-deuda-record/1/1 HTTP/1.1
Content-Type: application/json

###crear registro de la suma de la deuda 
POST http://localhost:2000/api/v1/add-deuda-record HTTP/1.1
Content-Type: application/json

{
    "idDeuda": 1,
    "fecha": "enero 2023",
    "producto": "pera",
    "valor": 20000
}

##### pedir registro de los abonos de las deudas
GET http://localhost:2000/api/v1/substractdeuda-record/1/1 HTTP/1.1
Content-Type: application/json

######## 

GET http://localhost:2000/api/v1/creditos/1 HTTP/1.1
Content-Type: application/json

#### crear credito

POST http://localhost:2000/api/v1/creditos HTTP/1.1
Content-Type: application/json


{
    "nombre" :"alberto",
    "phoneNumber": 1231231423, 
    "date": "jun/2/2020 "
}

###modificar credito
PUT http://localhost:2000/api/v1/creditos HTTP/1.1
Content-Type: application/json

{
    "nombre": "ander",
    "id_credito": "1",
    "fecha":"asd",
    "celular": "asd"
    
}

content
####

DELETE http://localhost:2000/api/v1/credits/12 HTTP/1.1
Content-Type: application/json


####    record credits

GET  http://localhost:2000/api/v1/addcredit-record/11/1 HTTP/1.1
Content-Type: application/json

####

DELETE http://localhost:2000/api/v1/addcredit-record/1 HTTP/1.1
Content-Type: application/json

###
PUT  http://localhost:2000/api/v1/addcredit-record HTTP/1.1
Content-Type: application/json


{
    "fecha": "1/2/2023 hora 5:50",
    "idRecord": 2,
    "producto": "pera",
    "valor": "20000"
}

#### buscar creditoitos 

GET http://localhost:2000/api/v1/creditos/find/ander  HTTP/1.1
Content-Content-Type: application/json

#####   crear


POST   http://localhost:2000/api/v1/addcredit-record HTTP/1.1
Content-Type: application/json


{
    "fecha": "5/3/2023",
    "idCredito": 11,
    "producto": "banano",
    "valor": "20000"
}


### actualizar productos 

PUT http://localhost:2000/api/v1/productos HTTP/1.1
Content-Type: application/json


{
    "unidades":"1" ,
    "nombre": "simeons",
    "costo": "20",
    "precio": "2000",
    "laboratorio": "genfar",
    "idProduct": 136
}


### get products

GET  http://localhost:2000/api/v1/productos/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c3VhcmlvIjoxMiwibm9tYnJlIjoidGFuaWEgbWFyY2VsYSIsImFjdGl2byI6MSwiZmVjaGEiOiIyMDIzLTA2LTE3IDIyOjMzOjM5LjgyNSIsImluaWNpbyI6MTcsImlhdCI6MTY4NzUyODEzOCwiZXhwIjoxNjg3NTY0MTM4fQ._cdMpnamU-sd5bIvTccoRxA_UH0k_HdbM9D6n6W0T_g

#### buscar productos 
GET  http://localhost:2000/api/v1/productos/buscar/aceta HTTP/1.1
Content-Type: application/json
#### crear producto

POST   http://localhost:2000/api/v1/productos HTTP/1.1
Content-Type: application/json


{
    "unidades":"12",
    "nombre":"anderson",
    "costo":"6546",
    "precio":"12000",
    "laboratorio":"gen",
}




### get abonos
GET http://localhost:2000/api/v1/substractcredit-record/1/1 HTTP/1.1
Content-Type: application/json


### post abonos
POST http://localhost:2000/api/v1/substractcredit-record/ HTTP/1.1
Content-Type: application/json

{
    "idCredito": 11,
    "fecha": "3/3/2023",
    "valor": 10000
}



#### put abonos
PUT http://localhost:2000/api/v1/substractcredit-record HTTP/1.1
Content-Type: application/json

{

    "idRecord": 3,
    "fecha": "3/3/2023",
    "valor": 10000

}


### delete abonos

DELETE http://localhost:2000/api/v1/substractcredit-record/ HTTP/1.1
Content-Type: application/json



### registrar usuario 
POST http://localhost:2000/api/v1/user HTTP/1.1
Content-Type: application/json

{
    "nombre": "tania marcela",
    "correo": "frutprosalud@gmail.com",
    "celular": "3145152824",
    "contraseña": "1234567891"
}

####  modificar usuario 
PUT http://localhost:2000/api/v1/user HTTP/1.1
Content-Type: application/json

{
    "nombre": "alejandro",
    "correo": "htsds@gmail.com",
    "celular": "3145152824",
    
}

### autentificacion  

POST http://localhost:2000/api/v1/user/aut HTTP/1.1
Content-Type: application/json

{
    "correo":  "trejostania554@gmail.com",
    "contraseña": "4897204648"
}


### eliminar

DELETE http://localhost:2000/api/v1/user/9 HTTP/1.1
Content-Type: application/json



#### recuperar contraseña

PUT  http://localhost:2000/api/v1/user/password HTTP/1.1
Content-Type: application/json

{
    "email": "garciacalvojhonanderson@gmail.com"
}


####update pass

PUT http://localhost:2000/api/v1/user/password HTTP/1.1
Content-Type: application/json

{
     "correo": "trejostania554@gmail.com",
    "celular": "3145152824"
}



#################     ventas #####################

## vender 
POST http://localhost:2000/api/v1/ventas HTTP/1.1
Content-Type: application/json


{
  "idVenta": 16,
  "valorTotal": 30000,
  "productosVendidos":[
    {
     "idProducto": 138, 
     "idVenta":16, 
     "producto": "acetaminofen", 
     "cantidad": 5, 
     "valor": 4000,
     "laboratorio": "genfar",
     "valor_total"
    },
    {
     "idProducto": 138, 
     "idVenta": 16, 
     "producto": "anesecia", 
     "cantidad": 2, 
     "valor": 4000,
     "laboratorio": "genfar",
     "valor_total"

    },{
     "idProducto": 138, 
     "idVenta": 16, 
     "producto": "sellos", 
     "cantidad": 2, 
     "valor": 4000,
     "laboratorio": "genfar",
     "valor_total"
    }
  ]
}


####  optener ventas 


GET http://localhost:2000/api/v1/ventas/history/26-26-2023/1 HTTP/1.1
Content-Type: application/json

####
GET http://localhost:2000/api/v1/ventas/history/all HTTP/1.1
Content-Type: application/json
####
GET http://localhost:2000/api/v1/ventas/graficos HTTP/1.1
Content-Type: application/json

##### optener productos vendidos de cada venta
GET http://localhost:2000/api/v1/ventas/productosventas/155 HTTP/1.1
Content-Type: application/json



#### buscar productos para venter
GET http://localhost:2000/api/v1/ventas/buscar/acetami HTTP/1.1
Content-Type: application/json


##### lista de ventas 

#### optener lista 
GET http://localhost:2000/api/v1/lista HTTP/1.1

### crear lista
POST http://localhost:2000/api/v1/lista HTTP/1.1
Content-Type: application/json

{
    "nombre": "acetamino",
    "laboratorio":"genfar",
    "unidades": 3,
    "precio": 2000,
    "valorTotal": 6000,
    "id_producto": 125
}

###modificar lista
PUT http://localhost:2000/api/v1/lista HTTP/1.1
Content-Type: application/json

{
    "idProducto": 123,
    "unidades": 1,
    "valorTotal": 2000
}

#### eliminar de la lista
DELETE http://localhost:2000/api/v1/lista/125 HTTP/1.1

#### eliminar toda la lista
DELETE http://localhost:2000/api/v1/lista/all HTTP/1.1


### rutas api gastos 

POST http://localhost:2000/api/v1/gastos/creargastos HTTP/1.1
Content-Type: application/json

{
    "idGasto" : "123",
    "idUsuario" : "2",
    "descripcion" : "hola a todos",
    "valorGasto" : "12222",
    "fecha" : "8/09/2021"
}

### optener gastos
GET http://localhost:2000/api/v1/gastos/optenergastos HTTP/1.1


### optener gastos detalles
GET http://localhost:2000/api/v1/gastos/detallesgastos/ HTTP/1.1


### eliminar gastos 
GET http://localhost:2000/api/v1/gastos/eliminargastos/212 HTTP/1.1

### actualizar 
GET http://localhost:2000/api/v1/gastos/modificargastos HTTP/1.1

{

}

### optener baance 
GET http://localhost:2000/api/v1/metrica/balance HTTP/1.1
